"""Visual assets used inside an experience page: provenance, licence and packaging (the asset-production seam).

A page may show an approved image - drawn in-house or generated by an external provider - as part of the experience
itself. The page stays the single source of visual truth: the reel maker records the page, so the same image reaches
the reel with no separate media pipeline (docs/VISUAL_ASSETS.md).

Registry: tools/visual_library.json, the visual twin of tools/reel-maker/audio_library.json.

    { "assetId":   "vis-<slug>",                         lower-case words joined by hyphens
      "mediaType": "image/png" | "image/jpeg" | "image/webp",
      "source":    "generated"                           PrayogX code made it   -> "generator": the script
                 | "external",                           a provider made it     -> "provider", "model",
                                                                                    "licenseDocument" (kept in the repo)
      "license": "...", "licenseVerified": true, "commercialUse": true,
      "permittedUse": ["web", "instagram", "youtube", ...],   web for the page; instagram + youtube because reels record it
      "attributionRequired": false, "attributionText": "",
      "file":   "tools/visual-assets/<assetId>.<ext>",   the approved original, kept in the repository
      "sha256": "<64 hex>" }                             of that file, and of the bytes embedded in the page

A page uses an asset by declaring <meta name="px-visual-asset" content="<assetId>"> and embedding the exact approved
bytes as a data:<mediaType>;base64,... URI, drawn on its canvas. Nothing is fetched at run time: the one-file rule
(docs/SIMULATION_STANDARDS.md §2) is kept, with no exception. Video is not supported: it cannot be stepped by the
recorder's clock and would need an owner-approved exception to the one-file rule.
"""
import base64
import hashlib
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBRARY = os.path.join("tools", "visual_library.json")
ASSET_DIR = "tools/visual-assets/"

ASSET_ID_RE = re.compile(r"^vis-[a-z0-9]+(?:-[a-z0-9]+)*$")
ASSET_ID_MAX = 64
MEDIA_TYPES = {"image/png": (".png",), "image/jpeg": (".jpg", ".jpeg"), "image/webp": (".webp",)}
SOURCES = ("generated", "external")
REQUIRED_USE = ("web", "instagram", "youtube")
MAX_BYTES = 2 * 1024 * 1024                      # embedded in index.html: pages must stay fast on ordinary phones
FIELDS = ("assetId", "mediaType", "source", "generator", "provider", "model", "license", "licenseVerified",
          "licenseDocument", "commercialUse", "permittedUse", "attributionRequired", "attributionText", "file", "sha256")

META_RE = re.compile(r'<meta\s+name=["\']px-visual-asset["\']\s+content=["\']([^"\']*)["\']\s*/?>', re.I)
DATA_URI_RE = re.compile(r"data:(image/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)")
REMOTE_RE = re.compile(r"""(?:\bsrc\s*=\s*|\burl\(\s*|\.src\s*=\s*|\bposter\s*=\s*)["']?\s*(?:https?:)?//""", re.I)


class VisualAssetError(Exception):
    pass


def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def load_library(root=ROOT):
    """{assetId: record}. The registry is required; an empty one is valid."""
    with open(os.path.join(root, LIBRARY), encoding="utf-8") as f:
        return {a.get("assetId"): a for a in json.load(f).get("assets", []) if isinstance(a, dict)}


def asset_problems(a, root=ROOT):
    """Everything wrong with one record (empty list = usable)."""
    if not isinstance(a, dict):
        return ["a visual asset record must be an object"]
    aid = a.get("assetId")
    where = "visual asset %r" % aid
    why = []
    if not isinstance(aid, str) or not ASSET_ID_RE.match(aid) or len(aid) > ASSET_ID_MAX:
        why.append("assetId must look like vis-<slug> (lower case, hyphens, at most %d characters)" % ASSET_ID_MAX)
    for k in a:
        if k not in FIELDS:
            why.append("%r is not a visual asset field (%s)" % (k, ", ".join(FIELDS)))
    mt = a.get("mediaType")
    if mt not in MEDIA_TYPES:
        why.append("mediaType %r is not one of %s (video needs an owner-approved exception)" % (mt, ", ".join(MEDIA_TYPES)))
    src = a.get("source")
    if src == "generated":
        if not a.get("generator"):
            why.append("a generated asset names its generator (the PrayogX script that made it)")
    elif src == "external":
        if not a.get("provider") or not a.get("model"):
            why.append("an external asset names its provider and model")
        doc = a.get("licenseDocument")
        if not doc or not os.path.isfile(os.path.join(root, doc)):
            why.append("no licence document kept in the repository")
    else:
        why.append("source %r is not one of %s" % (src, ", ".join(SOURCES)))
    if a.get("licenseVerified") is not True:
        why.append("licence not verified")
    if a.get("commercialUse") is not True:
        why.append("commercial use not permitted")
    if not (a.get("license") or "").strip():
        why.append("no licence text")
    use = a.get("permittedUse") or []
    missing = [u for u in REQUIRED_USE if u not in use]
    if missing:
        why.append("permittedUse lacks %s (the page is on the web and reels record it)" % ", ".join(missing))
    if a.get("attributionRequired") and not (a.get("attributionText") or "").strip():
        why.append("attribution required but no attribution text")
    f, digest = a.get("file"), a.get("sha256")
    if not isinstance(digest, str) or not re.match(r"^[0-9a-f]{64}$", digest):
        why.append("sha256 must be 64 lower-case hex characters")
    if not isinstance(f, str) or not f.startswith(ASSET_DIR):
        why.append("file must be kept under %s" % ASSET_DIR)
    elif mt in MEDIA_TYPES and not f.lower().endswith(MEDIA_TYPES[mt]):
        why.append("file extension does not match mediaType %s" % mt)
    elif not os.path.isfile(os.path.join(root, f)):
        why.append("file missing")
    else:
        with open(os.path.join(root, f), "rb") as fh:
            data = fh.read()
        if len(data) > MAX_BYTES:
            why.append("file is %d bytes; an embedded asset may be at most %d" % (len(data), MAX_BYTES))
        if sha256_bytes(data) != digest:
            why.append("file sha256 does not match the approved file")
    return ["%s: %s" % (where, w) for w in why]


def library_problems(root=ROOT):
    """Everything wrong with tools/visual_library.json."""
    path = os.path.join(root, LIBRARY)
    try:
        with open(path, encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, ValueError) as exc:
        return ["%s cannot be read: %s" % (LIBRARY, exc)]
    assets = doc.get("assets") if isinstance(doc, dict) else None
    if not isinstance(assets, list):
        return ["%s: assets must be a list" % LIBRARY]
    out, seen = [], set()
    for a in assets:
        out.extend(asset_problems(a, root))
        aid = a.get("assetId") if isinstance(a, dict) else None
        if aid in seen:
            out.append("visual asset %r: listed twice" % aid)
        seen.add(aid)
    return out


def check_asset(lib, asset_id, root=ROOT):
    """The record, or VisualAssetError: unlisted, unlicensed or altered assets are refused (as audio.check_asset)."""
    a = lib.get(asset_id)
    if not a:
        raise VisualAssetError("visual asset %r is not in %s - unknown provenance, not used" % (asset_id, LIBRARY))
    why = asset_problems(a, root)
    if why:
        raise VisualAssetError("; ".join(why))
    return dict(a)


def declared(html):
    return [m.strip() for m in META_RE.findall(html or "")]


def page_problems(html, lib, root=ROOT):
    """A page that declares visual assets: each is approved and embedded byte for byte; nothing visual is remote.
    A page that declares none is not this seam's business (empty list)."""
    ids = declared(html)
    if not ids:
        return []
    out = []
    embedded = {}
    for mt, b64 in DATA_URI_RE.findall(html):
        try:
            embedded.setdefault(sha256_bytes(base64.b64decode(b64, validate=True)), mt)
        except ValueError:
            continue
    for aid in sorted(set(ids), key=ids.index):
        try:
            a = check_asset(lib, aid, root)
        except VisualAssetError as exc:
            out.append(str(exc))
            continue
        if embedded.get(a["sha256"]) != a["mediaType"]:
            out.append("visual asset %r: the page does not embed the approved bytes as a data:%s;base64 URI"
                       % (aid, a["mediaType"]))
    if REMOTE_RE.search(html):
        out.append("the page loads a visual from the network; approved assets are embedded, never fetched")
    return out
